NumPy peut être installé sur un PC à l'aide de **pip ou brew**, mais si l'utilisateur utilise le Jupyter Notebook, il n'est pas nécessaire de l'installer. NumPy est déjà installé dans Jupyter Notebook. Je vais vous suggérer d'utiliser le bloc-notes Jupyter comme IDE car nous exécutons tout le code du bloc-notes Jupyter. Nous l'avons déjà montré au chapitre. Premiers pas avec les bibliothèques Python, comment installer Anaconda, qui est une suite complète pour l'analyse des données. Les tableaux NumPy sont une série d'éléments homogènes. Homogène signifie que le tableau aura tous les éléments du même type de données. Créons un tableau en utilisant NumPy. Vous pouvez créer un tableau à l'aide de la fonction array () avec une liste d'éléments. Les utilisateurs peuvent également corriger le type de données d'un tableau. Les types de données possibles sont bool, int, float, long, double et long double.

Voyons comment créer un tableau vide:

In [2]:
# Creating an array
import numpy as np
a = np.array([2,4,6,8,10])
print(a)

[ 2  4  6  8 10]


Une autre façon de créer un tableau NumPy est d'utiliser arange (). Il crée un tableau NumPy régulièrement espacé. Trois valeurs - start, stop et step - peuvent être transmises à la fonction arange (start, [stop], step). Le début est la valeur initiale de la plage, l'arrêt est la dernière valeur de la plage et le pas est l'incrément dans cette plage. Le paramètre d'arrêt est obligatoire. Dans l'exemple suivant, nous avons utilisé 1 comme paramètre de départ et 11 comme paramètre d'arrêt. La fonction arange (1,11) renverra 1 à 10 valeurs avec un pas car le pas est, par défaut, 1. La fonction arrange () génère une valeur qui est inférieure de un à la valeur du paramètre stop. Comprenons cela à travers l'exemple suivant:

In [3]:
# Creating an array using arange()
import numpy as np
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


Outre les fonctions array () et arange (), il existe d'autres options, telles que zeros (), ones (), full (), eye () et random (), qui peuvent également être utilisées pour créer un tableau NumPy , car ces fonctions sont des espaces réservés initiaux. Voici une description détaillée de chaque fonction:

+ zeros (): La fonction zeros () crée un tableau pour une dimension donnée avec tous les zéros.

+ ones (): La fonction ones () crée un tableau pour une dimension donnée avec tous les uns.

+ fulls (): La fonction full () génère un tableau avec des valeurs constantes.

+ eyes (): la fonction eye () crée une matrice d'identité.

+ random (): La fonction random () crée un tableau avec une dimension donnée.

Comprenons ces fonctions à travers l'exemple suivant:

In [5]:
import numpy as np
# Create an array of all zeros
p = np.zeros((3,3))
print(p)
# Create an array of all ones
q = np.ones((2,2))
print(q)
# Create a constant array
r = np.full((2,2), 4)

print(r)
# Create a 2x2 identity matrix
s = np.eye(4)
print(s)
# Create an array filled with random values
t = np.random.random((3,3))
print(t)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[4 4]
 [4 4]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.44330856 0.12092816 0.82515511]
 [0.36882698 0.50088047 0.89869541]
 [0.03265064 0.77712733 0.57939946]]


In the preceding code, we have seen some built-in functions for creating arrays with all-
zero values, all-one values, and all-constant values. After that, we have created the identity
matrix using the eye() function and a random matrix using the random.random()
function. Let's see some other array features in the next section.